### PR TITLE
Update nokogiri version since 1.4 is no longer supported. Find all do…

### PR DESCRIPTION
**Pull request by mhoskiso**
…mains will now also return whether domain protect is enabled.

### CODE REVIEW

**Comment by Malet** [comment]
@DMA57361 do you have access to merge this?

**Comment by DMA57361** [comment]
@Malet yes, I believe so. I'm not sure I've then got access to then publish a new version to RubyGems though; think you're the gem's owner?

**Comment by DMA57361** [comment]
Thanks @mhoskiso, we never actually started using this gem in production so haven't really been maintaining it. However, I'll try and cut a release and push it to RubyGem's for this change soon so that it works for those that are trying to use it.

**Comment by mhoskiso** [comment]
I just started using the gem myself, finally got tired of netsols partner portal :) For what I'm trying to accomplish, I'll also be adding the expiration and purchase date. I'll do another merge request if you want to include that before the rubygems update.

**Comment by DMA57361** [comment]
Sounds good.
I'll hang about for another merge request.

**Pull request merged**
